# Generated by Django 4.0.6 on 2022-07-19 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projecttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttag',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
