# Generated by Django 4.0.6 on 2022-07-21 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_projecttag_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measure', to='project.project'),
        ),
    ]
