# Generated by Django 4.0.6 on 2022-07-24 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_measure_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='parameter',
            new_name='parameter_float',
        ),
        migrations.AddField(
            model_name='parameter',
            name='parameter_char',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='parameter_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='project.measure'),
        ),
    ]
