# Generated by Django 4.0.6 on 2022-07-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rename_parameter_parameter_parameter_float_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='parameter_char',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
